version: '3.7'

services:
  auctionadmin:
    image: ${DOCKER_REGISTRY-}auctionadmin
    build:
      context: .
      dockerfile: AuctionAdmin/Dockerfile
    depends_on:
      - mongo

  auctionapi:
    image: ${DOCKER_REGISTRY-}auctionapi
    build:
      context: .
      dockerfile: AuctionAPI/Dockerfile
    depends_on:
      - mongo
      - auctionadmin
  
  mongo:
    image: ${DOCKER_REGISTRY-}mongo
    container_name: auctionDB
    restart: always
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: auctionAdmin
      MONGO_INITDB_ROOT_PASSWORD: Xm4XTDbDiFTGkBE
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata: